employee_tree/app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('employees', views.EmployeesView.as_view(), name='employees'),

]

employee_tree/employee_tree/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

employee_tree/app/models.py
from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.
class Position(models.Model):
    my_order = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False,
        )
    name = models.CharField(max_length=255)


    class Meta:
        ordering = ("my_order",)
        verbose_name_plural = "Positions"

    def __str__(self):
        return str(self.pk)

class Employee(MPTTModel):
    full_name = models.CharField(max_length=255)
    position = models.ForeignKey(Position, related_name="employee", on_delete=models.CASCADE)
    employment = models.DateTimeField()
    salary = models.FloatField()
    parent = TreeForeignKey(
        "self",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
    )

    class MPTTMeta:
        order_insertion_by = ["employment"]

    class Meta:
        verbose_name_plural = "Employess"

    def __str__(self):
        return self.full_name

employee_tree/app/views.py
from django.views.generic.list import ListView

from .models import Employee, Position

class IndexView(ListView):
    model = Employee
    context_object_name = 'employees'
    template_name = 'app/index.html'
    paginate_by = 50


class EmployeesView(IndexView):
    template_name = 'app/employees.html'

    def get_queryset(self):
        queryset =  super().get_queryset().values('full_name', 'employment', 'position__name', 'salary')
        self.request.session['sort'] = self.request.GET['sort']
        order = self.request.session['sort']

        if order:
             queryset = queryset.order_by(order)

        return queryset

employee_tree/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
        {% block title%} {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block content %}{% endblock %}
    </div>

</body>
</html>

employee_tree/app/templates/app/employees.html
{% extends 'app/base.html'%}

{% block title%}  {% endblock %}
{% load mptt_tags %}

{% block content %}
    <form action="{% url 'app:employees' %}" method="GET">
        <label>Сортировать по:</label>
        <select name="sort">
          <option value="full_name">ФИО</option>
          <option value="position">Должности</option>
          <option value="employment">Дате трудоустройства</option>
          <option value="salary">Зарплате</option>
        </select>
        <input type="submit">
    </form>
    <div>
        <ul>
            {% for node in employees %}
                <li>
                    {{node.full_name}}
                    <ul>
                        <li>{{node.employment}}</li>
                        <li>{{node.position__name}}</li>
                        <li>{{node.salary}}</li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

employee_tree/app/templates/app/index.html
{% extends 'app/base.html'%}
{% load mptt_tags %}

{% block title%} Главная страница {% endblock %}

{% block content %}
    <div>
        <ul>
            {% recursetree employees %}
                <li>
                    <strong>{{node.position.name}}:</strong> {{node.full_name}}
                    {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                    {% endif %}
                </li>
            {% endrecursetree %}
        </ul>
    </div>
{% endblock %}